# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ACCEL_MANAGER accel_manager)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ACTIVITY activity)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ALARMS alarms)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ANALYTICS analytics)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ANIMATION_SERVICE animation_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_CACHE app_cache)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_FETCH_ENDPOINT app_fetch_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_GLANCES app_glances)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_INBOX_SERVICE app_inbox_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_MESSAGE app_message)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_ORDER_ENDPOINT app_order_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_APP_OUTBOX_SERVICE app_outbox_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_AUDIO_ENDPOINT audio_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_BATTERY battery)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_BLOB_DB blob_db)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_BLUETOOTH bluetooth)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_BOOT_SPLASH boot_splash)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_CLOCK clock)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_COMM_SESSION comm_session)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_COMPOSITOR compositor)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_CONTACTS contacts)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_DATA_LOGGING data_logging)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_DEBOUNCED_CONNECTION_SERVICE debounced_connection_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ECOMPASS ecompass)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_EVENT_SERVICE event_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_EVENTED_TIMER evented_timer)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_FILESYSTEM filesystem)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_FIRMWARE_UPDATE firmware_update)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_GET_BYTES get_bytes)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_HEALTH_SYNC_ENDPOINT health_sync_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_HRM hrm)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_I18N i18n)
add_subdirectory(imaging)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_IDLE_WATCHDOG idle_watchdog)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_LIGHT light)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_MUSIC music)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_NEW_TIMER new_timer)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_NOTIFICATIONS notifications)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_ORIENTATION_MANAGER orientation_manager)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PERSIST persist)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PHONE_CALL phone_call)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PHONE_PP phone_pp)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PING ping)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_POLL_REMOTE poll_remote)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PRF_UPDATE prf_update)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PROCESS_MANAGEMENT process_management)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PROTOBUF_LOG protobuf_log)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_PUT_BYTES put_bytes)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_REGISTRY_ENDPOINT registry_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_REGULAR_TIMER regular_timer)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SEND_TEXT_SERVICE send_text_service)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SERVICES_COMMON services_common)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SERVICES_NORMAL services_normal)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SETTINGS settings)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SHARED_PRF_STORAGE shared_prf_storage)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SPEAKER speaker)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_STATIONARY stationary)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_STOPWATCH stopwatch)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_SYSTEM_TASK system_task)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_TICK_TIMER tick_timer)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_TIMELINE timeline)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_TIMEZONE_DATABASE timezone_database)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_TOUCH touch)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_VIBE_PATTERN vibe_pattern)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_VIBES vibes)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_VOICE voice)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_VOICE_ENDPOINT voice_endpoint)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_WAKEUP wakeup)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_WEATHER weather)
pbl_add_subdirectory_ifdef(CONFIG_SERVICE_WELLBEING wellbeing)

pbl_library()
pbl_library_sources(services.c)
